flags = -D_JUDGE_ -D_GLIBCXX_DEBUG -O2 -Wall -Wextra -Werror -Wno-sign-compare -std=c++11


program.exe: program.o Alfabets.o Alfabet.o Missatges.o Encriptacions.o
	g++ -o program.exe *.o

program.o: program.cc
	g++ -c program.cc $(flags)

Alfabets.o: Alfabets.cc
	g++ -c Alfabets.cc $(flags)

Missatges.o: Missatges.cc
	g++ -c Missatges.cc $(flags)

Encriptacions.o: Encriptacions.cc
	g++ -c Encriptacions.cc $(flags)

Alfabet.o: Alfabet.cc
	g++ -c Alfabet.cc $(flags)

clean:
	rm -f *.o
	rm -f *.exe